### ISSUE TITLE
M290 not supported in Klipper

### ISSUE THREAD

**Issue by sarumpaet** [jneilliii/OctoPrint-BabyStepping#2]
Klipper for some reason doesn't support M290, can you make this configurable to use [SET_GCODE_OFFSET Z_ADJUST=_relative_value_ MOVE=1](https://github.com/Klipper3d/klipper/blob/master/docs/G-Codes.md#set_gcode_offset)?

Thanks for the nice plugin!

**Comment by jneilliii** [comment]
I'm not super familiar with Klipper, but know that one of it's strengths is the ability to create your own [macros](https://www.klipper3d.org/Command_Templates.html). I believe the below would translate the M290 command into klipper compatible command. 

```
[gcode_macro M290]
gcode:
  SET_GCODE_OFFSET Z_ADJUST={ params.Z|float } MOVE=1
```

**Comment by sarumpaet** [comment]
Good point! I just switched to Klipper+Octoprint. :)

I noticed one can simply set up buttons via Octoprint config, so I'll go with this in `.octoprint/config.yaml`:
```
controls:
- children:
  - command: SET_GCODE_OFFSET Z_ADJUST=0.05 MOVE=1
    name: Up
  - command: SET_GCODE_OFFSET Z_ADJUST=-0.05 MOVE=1
    name: Down
  layout: vertical
  name: Babystepping
```

Thanks!
